# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
