# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-28 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190528_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='needed_know',
            field=models.CharField(default='\u6682\u65f6\u8fd8\u6ca1\u66f4\u65b0', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='\u5f85\u4f1a\u513f', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
