# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20190528_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='\u5f85\u4f1a\u513f', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
    ]
