# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-30 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190522_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default='18', max_length=5, verbose_name='\u5e74\u9f84'),
        ),
    ]
